INSERT INTO tbl_tipo_rutina(nombre, descripcion)
VALUES

    ('Full Body',
     'Entrenamiento de cuerpo completo en una sesión'),

    ('Torso Pierna',
     'División superior e inferior del cuerpo'),

    ('Push Pull Legs',
     'División por movimientos de empuje, jalón y pierna'),

    ('Bro Split',
     'Un grupo muscular principal por día'),

    ('Weider',
     'Rutinas divididas por grupos musculares'),

    ('Fuerza 5x5',
     'Rutina enfocada en progresión de cargas'),

    ('Circuito',
     'Entrenamiento enfocado en resistencia muscular');