INSERT INTO tbl_rutinas (
    id_usuario,
    id_objetivo,
    id_tipo_rutina,
    nombre,
    descripcion
)
VALUES
    (
        1,
        1,
        1,
        'Hipertrofia Full Body',
        'Rutina enfocada en ganar masa muscular trabajando todos los grupos musculares'
    ),
    (
        1,
        1,
        2,
        'Hipertrofia Torso Pierna',
        'División superior e inferior del cuerpo enfocada en hipertrofia'
    ),
    (
        1,
        1,
        3,
        'Hipertrofia Push Pull Legs',
        'División por empuje, jalón y pierna'
    ),
    (
        1,
        2,
        6,
        'Fuerza 5x5',
        'Rutina enfocada en progresión de cargas'
    );